### ISSUE TITLE
Databse plugin exception when removing old entries

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/plugins#473]
If the database is under stress the remove old entries method can't be executed successfully. That's what to expect but maybe the error could be catched somehow in a nicer way?
```
Feb 05 14:54:51 ERROR    lib.db            Can not execute query: DELETE FROM log WHERE (item_id = %(id)s                                      ) AND (time    = %(time)s          OR 1 = %(time_flag)s         ) AND (time    > %(time_start)s    OR 1 = %(time_start_flag)s   ) AND (time    < %(time_end)s      OR 1 = %(time_end_flag)s     ) AND (changed = %(changed)s       OR 1 = %(changed_flag)s      ) AND (changed > %(changed_start)s OR 1 = %(changed_start_flag)s) AND (changed < %(changed_end)s   OR 1 = %(changed_end_flag)s  );     (args OrderedDict([('id', 451), ('time', None), ('time_flag', 1), ('time_start', None), ('time_start_flag', 1), ('time_end', 1604584284758), ('time_end_flag', 0), ('changed', None), ('changed_flag', 1), ('changed_start', None), ('changed_start_flag', 1), ('changed_end', None), ('changed_end_flag', 1)])): (1205, 'Lock wait timeout exceeded; try restarting transaction')
Feb 05 14:54:51 ERROR    plugins.database  Database: Error for query DELETE FROM log WHERE (item_id = 451                                      ) AND (time    = None          OR 1 = 1         ) AND (time    > None    OR 1 = 1   ) AND (time    < 1604584284758      OR 1 = 0     ) AND (changed = None       OR 1 = 1      ) AND (changed > None OR 1 = 1) AND (changed < None   OR 1 = 1  );    : (1205, 'Lock wait timeout exceeded; try restarting transaction')
Feb 05 14:54:51 ERROR    plugins.database.Remove old Method plugins.database.Remove old exception: (1205, 'Lock wait timeout exceeded; try restarting transaction')
Traceback (most recent call last):
  File "/usr/local/smarthome/lib/scheduler.py", line 664, in _task
    obj()
  File "/usr/local/smarthome/plugins/database/__init__.py", line 1162, in remove_older_than_maxage
    self.deleteLog(item_id, time_end=timestamp_end, with_commit=False)
  File "/usr/local/smarthome/plugins/database/__init__.py", line 624, in deleteLog
    self._execute(self._prepare("DELETE FROM {log} WHERE " + condition), params, cur=cur)
  File "/usr/local/smarthome/plugins/database/__init__.py", line 1229, in _execute
    self._query(self._db.execute, query, params, cur)
  File "/usr/local/smarthome/plugins/database/__init__.py", line 1259, in _query
    raise e
  File "/usr/local/smarthome/plugins/database/__init__.py", line 1256, in _query
    tuples = func(self._prepare(query), params, cur=cur)
  File "/usr/local/smarthome/lib/db.py", line 324, in execute
    result = c.execute(stmt, args)
  File "/home/smarthome/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/smarthome/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/smarthome/.local/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/smarthome/.local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/smarthome/.local/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/smarthome/.local/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/smarthome/.local/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/smarthome/.local/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1205, 'Lock wait timeout exceeded; try restarting transaction')

```

**Comment by msinn** [comment]
> 'Lock wait timeout exceeded; try restarting transaction'

How large is your database?
Is the **Lock wait timeout** something that can be configured in MySQL?

**Comment by onkelandy** [comment]
As far as I see it can be configured. Ich wollte aber primär drauf raus, dass der Fehler im Plugin sauber abgefangen wird, ohne dass die ganze Wurscht ins Log geschrieben wird.
