### ISSUE TITLE
Vacations Plugin: Error raised due to temporyry error at name resolution

### ISSUE THREAD

**Issue by bmxp** [smarthomeNG/plugins#516]
```
2021-05-15  13:31:59 ERROR    plugins.vacations.plugins.vacations Method plugins.vacations.plugins.vacations exception: HTTPSConnectionPool(host='ferien-api.de', port=443): Max retries exceeded with url: /api/v1/holidays (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f51954fec18>: Failed to establish a new connection: [Errno -3] Temporärer Fehler bei der Namensauflösung'))
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
>     (self._dns_host, self.port), self.timeout, **extra_kw)
>   File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 57, in create_connection
>     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
>   File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno -3] Temporärer Fehler bei der Namensauflösung
```

maybe we can catch this error in a more beautiful way ...

**Comment by psilo909** [comment]
any idea how to "provoce" it, so I could test that?

**Comment by bmxp** [comment]
Not really. I think it might have to do with an Update of the FritzBox and a network that is not available then. At least the error description is fine for me and understandable but this is not a code error at all, it just does not look nice to see the Traceback here

**Comment by Morg42** [comment]
If I understand the plugin code correctly, this error originates in the imported ferien-api module. It _could_ be try/except-ed by enclosing the ferien call, but this doesn't really seem sensible. 
If this should really be taken care of, I'd suggest opening an issue with ferien-api...

**Comment by msinn** [comment]
Will something happen with this issue or should it be ignored/closed?

**Comment by psilo909** [comment]
@Morg42 perhaps you are right, perhaps i also added it after reading the issue and forgot to comment. I am not sure if it really fixed all of the problem - but on my side it never occurred

**Comment by psilo909** [comment]
@Morg42 also the master has the try except https://github.com/smarthomeNG/plugins/blob/master/vacations/__init__.py#L68

So I am not sure if this really catches everything. In theory it should.

**Comment by msinn** [comment]
SmartHomeNG v1.9.4 has been released
