### ISSUE TITLE
knx problem: Threads can only be started once

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/plugins#596]
Got this error today, KNX Plugin Version 1.8.0:
```
Mär 29 11:37:11 ERROR    KNX poll jalousien.eg.osten_buero.hoehe Method KNX poll jalousien.eg.osten_buero.hoehe exception: threads can only be started once
Traceback (most recent call last):
  File "/usr/local/smarthome/lib/scheduler.py", line 659, in _task
    obj(**value)
  File "/usr/local/smarthome/plugins/knx/__init__.py", line 252, in _poll
    self.groupread(kwargs['ga'])
  File "/usr/local/smarthome/plugins/knx/__init__.py", line 243, in groupread
    self._send(pkt)
  File "/usr/local/smarthome/plugins/knx/__init__.py", line 191, in _send
    self._client.send(send)
  File "/usr/local/smarthome/lib/network.py", line 648, in send
    self.connect()
  File "/usr/local/smarthome/lib/network.py", line 618, in connect
    self.__connect_thread.start()
  File "/usr/lib/python3.9/threading.py", line 869, in start
    raise RuntimeError("threads can only be started once")
RuntimeError: threads can only be started once
Mär 29 11:37:11 ERROR    KNX poll jalousien.og.osten_stiegenhaus.hoehe Method KNX poll jalousien.og.osten_stiegenhaus.hoehe exception: threads can only be started once
Traceback (most recent call last):
  File "/usr/local/smarthome/lib/scheduler.py", line 659, in _task
    obj(**value)
  File "/usr/local/smarthome/plugins/knx/__init__.py", line 252, in _poll
    self.groupread(kwargs['ga'])
  File "/usr/local/smarthome/plugins/knx/__init__.py", line 243, in groupread
    self._send(pkt)
  File "/usr/local/smarthome/plugins/knx/__init__.py", line 191, in _send
    self._client.send(send)
  File "/usr/local/smarthome/lib/network.py", line 648, in send
    self.connect()
  File "/usr/local/smarthome/lib/network.py", line 618, in connect
    self.__connect_thread.start()
  File "/usr/lib/python3.9/threading.py", line 869, in start
    raise RuntimeError("threads can only be started once")
RuntimeError: threads can only be started once
```
Any ideas where this problem originates from?
Respective item has knx_poll: 2/1/18

KNX Busmonitor log:
```
Mär 29 11:34:53 --------------------   Init SmartHomeNG v1.9.1.1-ce26bff4.develop   --------------------;
Mär 29 11:34:53 Running in Python interpreter 'v3.9.2 final', from directory /usr/local/smarthome;
Mär 29 11:34:53  - on Linux-5.10.103-v7l+-armv7l-with-glibc2.31 (pid=1129);
Mär 29 11:35:03  - Nutze Feiertage für Land 'AT', Provinz 'V', benutzerdefinierte(r) Feiertag(e) nicht definiert;
Mär 29 11:37:13 ;1.1.34;3/3/97;180.96;
Mär 29 11:37:13 ;1.1.34;3/3/97;180.96;
Mär 29 11:37:13 ;1.1.44;4/5/24;False;
...

Mär 29 11:37:28 ;1.1.4;2/1/18;0.0;
```
KNX Log:
Mär 29 11:36:10 CEST INFO     plugins.knx       Main         Item jalousien.eg.osten_buero.hoehe is polled on GA 2/1/18 every 60.0 seconds  --  (__init__.py:parse_item:618)
and some more polling info, then nothing.

**Comment by msinn** [comment]
Should be fixed by updates to lib.network

**Comment by msinn** [comment]
SmartHomeNG v1.9.2 with the resolution has been released
