### ISSUE TITLE
husky: api connection error

### ISSUE THREAD

**Issue by gruberth** [smarthomeNG/plugins#597]
Since a few days the connection to the husqvarna automover via the plugin seems not working anymore.  The andriod app still works as always. Before this I had the plugin running for several weeks without any problems.

When I am looking into the log there is always the same 404 error and the plugin pauses. 
Can anybody confirm this? Is it possible that husqvarna changed the url to connect to the api from the one used in the plugin now definitive to the new one (https://api.amc.husqvarna.dev/v1)?

Here is my shortened log from a startup of SmarthomeNG:

```
2022-03-31  12:13:50 NOTICE   lib.smarthome       --------------------   Init SmartHomeNG v1.9.1-master (8133e714)   --------------------
2022-03-31  12:13:50 NOTICE   lib.smarthome       Running in Python interpreter 'v3.8.10 final', from directory /usr/local/smarthome
2022-03-31  12:13:50 NOTICE   lib.smarthome        - on Linux-5.4.0-105-generic-x86_64-with-glibc2.29 (pid=7986)
2022-03-31  12:13:58 DEBUG    plugins.husky       parse STATE item: mower connection state
2022-03-31  12:13:58 DEBUG    plugins.husky       adding valid state item mower connection state to wachlist husky_state=connection 
2022-03-31  12:13:58 DEBUG    plugins.husky       parse STATE item: activity name (CUTTING, MOVING, ...)
2022-03-31  12:13:58 DEBUG    plugins.husky       adding valid state item activity name (CUTTING, MOVING, ...) to wachlist husky_state=activity 
2022-03-31  12:13:58 DEBUG    plugins.husky       parse STATE item: System.Maehroboter.state.errormessage
2022-03-31  12:13:58 DEBUG    plugins.husky       adding valid state item System.Maehroboter.state.errormessage to wachlist husky_state=errormessage 
2022-03-31  12:13:58 DEBUG    plugins.husky       parse STATE item: System.Maehroboter.state.message
2022-03-31  12:13:58 DEBUG    plugins.husky       adding valid state item System.Maehroboter.state.message to wachlist husky_state=message 
2022-03-31  12:13:58 DEBUG    plugins.husky       parse STATE item: System.Maehroboter.state.color
2022-03-31  12:13:58 DEBUG    plugins.husky       adding valid state item System.Maehroboter.state.color to wachlist husky_state=color 
2022-03-31  12:13:58 DEBUG    plugins.husky       parse STATE item: System.Maehroboter.state.batterypercent
2022-03-31  12:13:58 DEBUG    plugins.husky       adding valid state item System.Maehroboter.state.batterypercent to wachlist husky_state=batterypercent 
2022-03-31  12:13:58 DEBUG    plugins.husky       parse CONTROL item: Start
2022-03-31  12:13:58 DEBUG    plugins.husky       adding valid command item Start to wachlist husky_control=START_3H 
2022-03-31  12:13:58 DEBUG    plugins.husky       parse CONTROL item: Start normal
2022-03-31  12:13:58 DEBUG    plugins.husky       adding valid command item Start normal to wachlist husky_control=START 
2022-03-31  12:13:58 DEBUG    plugins.husky       parse CONTROL item: Stop
2022-03-31  12:13:58 DEBUG    plugins.husky       adding valid command item Stop to wachlist husky_control=STOP 
2022-03-31  12:13:58 DEBUG    plugins.husky       parse CONTROL item: Park
2022-03-31  12:13:58 DEBUG    plugins.husky       adding valid command item Park to wachlist husky_control=PARK 
2022-03-31  12:13:58 DEBUG    plugins.husky       parse CONTROL item: Park until next Timer
2022-03-31  12:13:58 DEBUG    plugins.husky       adding valid command item Park until next Timer to wachlist husky_control=PARK_TIMER 
2022-03-31  12:13:58 DEBUG    plugins.husky       parse OPDATA item: Mähzeit in Millisekunden
2022-03-31  12:13:58 DEBUG    plugins.husky       adding valid operation data item Mähzeit in Millisekunden to wachlist husky_operating=CUTTING 
2022-03-31  12:13:58 DEBUG    plugins.husky       parse OPDATA item: Parkzeit in Millisekunden
2022-03-31  12:13:58 DEBUG    plugins.husky       adding valid operation data item Parkzeit in Millisekunden to wachlist husky_operating=PARKED 
2022-03-31  12:13:58 DEBUG    plugins.husky       parse OPDATA item: Ladezeit in Millisekunden
2022-03-31  12:13:58 DEBUG    plugins.husky       adding valid operation data item Ladezeit in Millisekunden to wachlist husky_operating=CHARGING 
2022-03-31  12:13:58 DEBUG    plugins.husky       parse OPDATA item: Bewegungszeit in Millisekunden
2022-03-31  12:13:58 DEBUG    plugins.husky       adding valid operation data item Bewegungszeit in Millisekunden to wachlist husky_operating=MOVING 
2022-03-31  12:13:58 DEBUG    plugins.husky       parse OPDATA item: Fehlerzeit in Millisekunden
2022-03-31  12:13:58 DEBUG    plugins.husky       adding valid operation data item Fehlerzeit in Millisekunden to wachlist husky_operating=ERROR 
2022-03-31  12:13:59 DEBUG    plugins.husky       Run method called
2022-03-31  12:13:59 INFO     plugins.husky       login with userid: ****.****@****.****
2022-03-31  12:13:59 NOTICE   lib.smarthome       --------------------   SmartHomeNG initialization finished   --------------------
2022-03-31  12:14:00 INFO     plugins.husky       Logged in successfully
2022-03-31  12:14:00 INFO     plugins.husky       login lifetime 863999
2022-03-31  12:14:00 INFO     plugins.husky       token updated
2022-03-31  12:14:00 ERROR    lib.plugin          Plugin 'husky' exception in run() method: 404 Client Error: Not Found for url: https://amc-api.dss.husqvarnagroup.net/v1/mowers
Traceback (most recent call last):
  File "/usr/local/smarthome/lib/plugin.py", line 676, in run
    self.plugin.run()
  File "/usr/local/smarthome/plugins/husky/__init__.py", line 175, in run
    self._select_mower()
  File "/usr/local/smarthome/plugins/husky/__init__.py", line 423, in _select_mower
    self.mowers = self.mowapi.list_robots()
  File "/usr/local/smarthome/plugins/husky/__init__.py", line 709, in list_robots
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://amc-api.dss.husqvarnagroup.net/v1/mowers
...
```

The first occourence of a failure was this 500 error but after this it worked again:
```
2022-03-27  10:48:04 DEBUG    plugins.husky       status received - but same timestamp - no update needed (True)
2022-03-27  10:49:04 DEBUG    plugins.husky       status received - but same timestamp - no update needed (True)
2022-03-27  10:50:08 ERROR    plugins.husky.husky_poll_service Method plugins.husky.husky_poll_service exception: 500 Server Error: Internal Server Error for url: https://amc-api.dss.husqvarnagroup.net/v1/mowers/*******-*******/status
Traceback (most recent call last):
  File "/usr/local/smarthome/lib/scheduler.py", line 657, in _task
    obj()
  File "/usr/local/smarthome/plugins/husky/__init__.py", line 340, in poll_device
    mower_status_v0 = self.mowapi.status()
  File "/usr/local/smarthome/plugins/husky/__init__.py", line 731, in status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://amc-api.dss.husqvarnagroup.net/v1/mowers/*******-*******/status
2022-03-27  10:51:05 DEBUG    plugins.husky       --- new status received:
2022-03-27  10:51:05 DEBUG    plugins.husky       **** [PARKED] - 100% (2022-03-27 10:50:15)
2022-03-27  10:51:05 DEBUG    plugins.husky       found 6 state items to update
...
```

and then the next day it startet to throw the 404 error countinuously:

```
2022-03-28  09:26:18 DEBUG    plugins.husky       status received - but same timestamp - no update needed (True)
2022-03-28  09:27:18 ERROR    plugins.husky.husky_poll_service Method plugins.husky.husky_poll_service exception: 404 Client Error: Not Found for url: https://amc-api.dss.husqvarnagroup.net/v1/mowers/*******-*******/status
Traceback (most recent call last):
  File "/usr/local/smarthome/lib/scheduler.py", line 657, in _task
    obj()
  File "/usr/local/smarthome/plugins/husky/__init__.py", line 340, in poll_device
    mower_status_v0 = self.mowapi.status()
  File "/usr/local/smarthome/plugins/husky/__init__.py", line 731, in status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://amc-api.dss.husqvarnagroup.net/v1/mowers/*******-*******/status
2022-03-28  09:28:18 ERROR    plugins.husky.husky_poll_service Method plugins.husky.husky_poll_service exception: 404 Client Error: Not Found for url: https://amc-api.dss.husqvarnagroup.net/v1/mowers/*******-*******/status
Traceback (most recent call last):
  File "/usr/local/smarthome/lib/scheduler.py", line 657, in _task
    obj()
  File "/usr/local/smarthome/plugins/husky/__init__.py", line 340, in poll_device
    mower_status_v0 = self.mowapi.status()
  File "/usr/local/smarthome/plugins/husky/__init__.py", line 731, in status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://amc-api.dss.husqvarnagroup.net/v1/mowers/*******-*******/status
....
```

**Comment by bmxp** [comment]
Thank you for your feedback. There is [this thread](https://knx-user-forum.de/forum/supportforen/smarthome-py/1061848-steuerung-automower/page2#post1757102) in knx-user-forum which adresses just this problem.
However I am not sure if @gamade can fix it soon or if he has time at all.

**Comment by gruberth** [comment]
#603
