### ISSUE TITLE
smartvisu plugin: error reading deprecated.yaml

### ISSUE THREAD

**Issue by wvhn** [smarthomeNG/plugins#670]
Hi,
with smartVISU v3.3 the last deprecated widget was moved from the section "deprecated" to "removed" in the "deprecated.yaml" file, leaving the "deprecated" section empty. This causes the following error in the smartvisu autogeneration plugin of SmarthomeNG:
```
2022-12-19  21:40:46 ERROR    plugins.smartvisu   SmartVisuInstallWidgets v3.3.0: Exception: 'NoneType' object is not iterable
> Traceback (most recent call last):
>   File "/usr/local/smarthome/plugins/smartvisu/__init__.py", line 123, in run
>     sv_iwdg = SmartVisuInstallWidgets(self)
>   File "/usr/local/smarthome/plugins/smartvisu/svinstallwidgets.py", line 55, in __init__
>     self.install_widgets(self._sh)
>   File "/usr/local/smarthome/plugins/smartvisu/svinstallwidgets.py", line 99, in install_widgets
>     self.copy_widgets( plgdir.replace('.', '/') )
>   File "/usr/local/smarthome/plugins/smartvisu/svinstallwidgets.py", line 149, in copy_widgets
>     self.plugin_instance.test_widget_for_deprecated_widgets(os.path.join(srcdir, fn))
>   File "/usr/local/smarthome/plugins/smartvisu/__init__.py", line 284, in test_widget_for_deprecated_widgets
>     for widget_name in self.deprecated_widgets:
> TypeError: 'NoneType' object is not iterable
2022-12-19  21:40:46 ERROR    plugins.smartvisu   SmartVisuGenerator: Exception: 'NoneType' object is not iterable
> Traceback (most recent call last):
>   File "/usr/local/smarthome/plugins/smartvisu/__init__.py", line 135, in run
>     svgen = SmartVisuGenerator(self, self.visu_definition)
>   File "/usr/local/smarthome/plugins/smartvisu/svgenerator.py", line 70, in __init__
>     self.pages()
>   File "/usr/local/smarthome/plugins/smartvisu/svgenerator.py", line 228, in pages
>     self.plugin_instance.test_item_for_deprecated_widgets(item)
>   File "/usr/local/smarthome/plugins/smartvisu/__init__.py", line 313, in test_item_for_deprecated_widgets
>     for widget in self.deprecated_widgets:
> TypeError: 'NoneType' object is not iterable
```  
A dummy entry as workaround is now in place but this should be fixed in the plugin.
Thanks to @gruberth for raising the [issue](https://github.com/Martin-Gleiss/smartvisu/issues/818)! 

Regards
Wolfram

**Comment by msinn** [comment]
SmartHomeNG v1.9.4 has been released
